spring:
  main:
    banner-mode: "off"
  application:
    name: orderProcessingSystem

  datasource:
    url: jdbc:postgresql://localhost:5432/orderprocessingsystem_db
    username: adminosp
    password: password123$
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      #ddl-auto: update
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

app:
  jwt:
    secret: 8Tm0lx6P1dSctoLxxlQ4ZSCwS+UByOdSItcQPd6V1CM=
    expiration-ms: 3600000