apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ops.fullname" . }}-config
  labels:
    {{- include "ops.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.app.profile | quote }}
  {{- if .Values.postgres.enabled }}
  SPRING_DATASOURCE_URL: {{ printf "jdbc:postgresql://%s:%v/%s" (include "ops.postgres.fullname" .) .Values.postgres.port .Values.postgres.database | quote }}
  {{- end }}
