apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ops.fullname" . }}-secret
  labels:
    {{- include "ops.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.jwt.secret | quote }}
  db-username: {{ .Values.postgres.username | quote }}
  db-password: {{ .Values.postgres.password | quote }}
